sonar.organization=bapp86
sonar.projectKey=bapp86_AUY1102-Pipeline

# Nombre del proyecto en SonarCloud
sonar.projectName=bapp86/AUY1102-Pipeline

# Dónde está el código fuente
sonar.sources=src

# Dónde están las pruebas
sonar.tests=test

# Lenguaje
sonar.language=ts

# Encoding
sonar.sourceEncoding=UTF-8

# Dónde está el reporte de cobertura de pruebas
sonar.typescript.lcov.reportPaths=coverage/lcov.info
